language: cpp
compiler:
  - gcc
script: 
  - mkdir -p tmp
  - pushd tmp 
  - cmake .. 
  - make
after_success:
  - ctest --output-on-failure || exit 1
addons:
  apt:
    sources:
    - git
    - build-essential
    - cmake
    - python
    - python-dev
    - libssl-dev 
    - libboost-all-dev
    - protobuf-compiler
    - python-protobuf
    - libprotobuf-dev
    - python-sphinx
    - libcrypto++-dev
    - libcrypto++
    - liblua5.1-0-dev
    - libgtest-dev
#before_install:
#  - sudo touch /usr/share/pyshared/google/protobuf/compiler/__init__.py
#  - sudo touch /usr/lib/python2.7/dist-packages/google/protobuf/compiler/__init__.py
sudo: false
notifications:
 irc:
  channels:
    - irc.freenode.net#nsclient
  on_success: always
  on_failure: always
  use_notice: true
  skip_join: true
